@startuml sequence-diagram

header Massage Reservation Sequence Diagram
title "Massage Reservation (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservations
participant "<<middleware>>\n:protect" as middlewareProtect
participant "<<controllers>>\n:reservations" as controllersReservations
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as reservationsDatabase

== 8. Admin edit any massage reservation. ==

client -> server ++: req.put('/api/v1/reservations/:id')
server -> routerReservations ++: app.use('/api/v1/reservations', reservations)
routerReservations -> middlewareProtect ++: protect()
middlewareProtect --> routerReservations --: next()
routerReservations -> controllersReservations ++: updateReservation()
controllersReservations -> modelReservation ++: findById(req.params.id)
modelReservation -> reservationsDatabase ++: ReservationSchema
reservationsDatabase --> modelReservation --: reservation
controllersReservations <-- modelReservation --: reservation
note right of controllersReservations: role == admin\nownership check skipped
controllersReservations -> modelReservation ++: findByIdAndUpdate(req.params.id, req.body, { new, runValidators })
modelReservation -> reservationsDatabase ++: ReservationSchema
reservationsDatabase --> modelReservation --: reservation
controllersReservations <-- modelReservation --: reservation
controllersReservations -> client --: response

@enduml
